### ISSUE TITLE
Error: No named parameter with the name 'scrollPhysics'

### ISSUE THREAD

**Issue by nordinenn** [LucaIaconelli/stripe-flutter#2]
Hey hope you are doing well . 
Im getting this errors .

Compiler message:
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_payments_stripe_sdk-1.0.5/lib/src/ui/components/payment_card_text_field.dart:361:21: Error: No named parameter with the name 'scrollPhysics'.
                    scrollPhysics: BouncingScrollPhysics(),
                    ^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/material/text_form_field.dart:81:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({
  ^^^^^^^^^^^^^

**Comment by LucaIaconelli** [comment]
Hello,

We removed that code and updated the repository.

Let us know if everything is ok now.

Thanks

**Comment by nordinenn** [comment]
Hi 
now its okay . 
thanks for your support
