### ISSUE TITLE
i can't find subtitle1 in TextIcon

### ISSUE THREAD

**Issue by nordinenn** [LucaIaconelli/stripe-flutter#3]
no subtitle1 property , i think you should remove it to subtitle (maybe its a tapping mistake)
? theme.textTheme.subtitle1.copyWith(
                  fontSize: widget.fontSize ?? 16,
                  color: isSelected

**Comment by LucaIaconelli** [comment]
I think that you need to update Flutter.

**Comment by nordinenn** [comment]
ah i will try 
thanks

**Comment by nordinenn** [comment]
can you write a clear example  , because i dont undestand somethings like backendUrl (about which backend you are talking )  . 
also there is any config for android or ios ?
Have great day

**Comment by LucaIaconelli** [comment]
Hey, 

You can use this example directly created by Stripe: https://stripe.com/docs/payments/integration-builder
