### ISSUE TITLE
3d secure redirect me to blank page

### ISSUE THREAD

**Issue by nordinenn** [LucaIaconelli/stripe-flutter#4]
Hey bro 
in testing mode 3d secure after click in complete redirect me to blank page , is that okay or something wrong happen with me . (thats okay in testing mode)

**Comment by LucaIaconelli** [comment]
Did you add a url scheme inside your app?

**Comment by nordinenn** [comment]
No where and how i can add it  ? plz (also im working with php as backend)

**Comment by LucaIaconelli** [comment]
You can follow this guide: (https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app)

After this, you need to add the returnUrlForSca parameter to the Stripe init.

**Comment by nordinenn** [comment]
Hey bro , 
I think everything going well just in test mode they don't ask me about the verification code because in dashboard they say the payment was succesed and verified by 3d secure , but 
the problem is when user finish payment we should close the browser and back to our application with the result of payment .
is that possible ?
thank you for your support bro  , keep working you have awesome package i really love it .

**Comment by LucaIaconelli** [comment]
Yes it’s possible with a url scheme (is just for that) 

Thanks

**Comment by nordinenn** [comment]
i have tried with this 
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="example.stripe.flutter"
                    android:scheme="stripesdk" />
            </intent-filter>

but it's still the same  . 
i'm really confused becuase i dont know how to make a url scheme .  
that need something to do in backend  ?

**Comment by LucaIaconelli** [comment]
No it's a frontend thing
