### ISSUE TITLE
3D-Secure problem on Android

### ISSUE THREAD

**Issue by ot-repo** [LucaIaconelli/stripe-flutter#7]
Hello,

First of all thanks for the great plugin!

I have a problem on Android. After I enter my credit card, a new browser opens, where I verify the payment through 3D secure mechanism. This is working without a problem. After my bank confirms the payment, the browser will forwarded to an empty page. On IOS it asks me whether I want to return my app. However on Android nothing happens. I only see the white page.

I am using the following two stripe dependencies:
flutter_payments_stripe_sdk: ^1.0.9
stripedart: ^1.0.5

I attach my AndroidManifest file as txt file.
[AndroidManifest.txt](https://github.com/LucaIaconelli/stripe-flutter/files/7479107/AndroidManifest.txt)

Thanks in advance!
Sinan

**Comment by ot-repo** [comment]
I have tried it on web application and seen the error attached here. I suppose the browser does not know the scheme stripesdk. On iOS we register that scheme with:

<key>CFBundleURLSchemes</key>
<array>
    <string>stripesdk</string>
</array>

however I haven't seen such scheme registration on Android.

I hope that helps to identify the problem.

Thank you.

**Comment by ot-repo** [comment]
After I have debugged the Crome browser, I have seen the warning in the console. Maybe it helps.

![flutter_android_error](https://user-images.githubusercontent.com/71355727/140433600-b5107d6c-cf2f-4077-9e3c-a3122226bff9.jpg)

Thank you.

**Comment by LucaIaconelli** [comment]
Hello, 

Can you try to follow [this](https://pub.dev/packages/uni_links) Android instructions and check if after this works?

Thanks

**Comment by ot-repo** [comment]
Hello,

thanks for the quick answer. It turns out that the deep link registration was not correct.

After I removed the android:host property, it worked fine! It should be as follows.

`<data android:scheme="stripesdk" />`

Thank you!
Best Regards
